### ISSUE TITLE
Unable to install on Android

### ISSUE THREAD

**Issue by denissovav** [Apollon77/hap-controller-node#217]
I believe the only dependency, which does not support Android, is @abandonware/noble,
I was able to install @abandonware/noble 1.9.2-23 to Android using local package with modified package[-lock].json by adding ('android' to OS list).
However, hap-controller does not check for / recognize installed @abandonware/noble 1.9.2-23 package.
Could you add check for installed @abandonware/noble v.1.9.2-23 and/or somehow disable OS check for @abandonware/noble v.1.9.2-23.
Thank you.

**Comment by Apollon77** [comment]
This poackage has 1.9.2-23 as dependency... So what exactly you get as error when installing it directly? ANd also: This library is not limitigng any OS or ssuch, this might just be the noble package directly, so the request to allow android needs to go to the noble library. this library can no do anything for you in this regard. Only thing is that you could check how you cvan tell npm to ignore install errors (maybe -f?)
