### ISSUE TITLE
Add some debug log on messages to allow to see whats happening inside

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/hap-controller-node#34]
WHile debugging my issue #31 I had bigger issues to see what the lib does.

If ok for you I would provide a PR to add "debug" lib into some of the files and add some basic logging.

Would that be ok for you?

**Comment by mrstegeman** [comment]
Yes, that would be fantastic.

**Comment by Apollon77** [comment]
see https://github.com/mrstegeman/hap-controller-node/pull/36
