### ISSUE TITLE
Question: subscribe/unsubscribe 

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/hap-controller-node#37]
@mrstegeman I have a question :-)

In HTTPClient the subscribe command returns the HTTPConnection and on unsubscribe this connection is provided back and used to unsubscribe. This makes sense, BUT after unsubscribe there is no "connection.close()" ... Is this forgotten or by intend? Would an unsubscribe also work with just closing that connection?

In GattClient on subscribe the GattConnection is returned and not disconnected, but the "unsubscribe" method is NOT taking this GattConnection for unsubscribe. So also here one connection is left open without a disconnect. The connection created in subscribe is used in the "event" cases to retrieve data.

In fact I see the dilemma with the current code structure. The subscribe allows (in HTTP case) to subscribe for X datapoints and the unsubscribe is not using the same set and I could unsubscribe for just some of them. But this means that the developer needs to take care to close the HTTP/GattConnections once he do not want to receive data anymore. or?

Thnak you for your thoughts on this

**Comment by Apollon77** [comment]
@mrstegeman But before we take over, also here it would be great to get your "knowledge from the past"

**Comment by mrstegeman** [comment]
The main issue here is that subscriptions are fundamentally different between the two. In Bluetooth, each characteristic subscription is a single persistent connection. Bluetooth chipsets are limited in the number of open connections they can maintain.

As for automatically closing things... In HTTP, the connection can be reused for other operations (and in many cases, should be). With the GATT connection, successive operations require re-pairing. However, I probably left out the auto-close from GATT just to maintain a semi-consistent API between the two.

**Comment by Apollon77** [comment]
Hm ... for Gatt there is in fact one connection which is initialized on subscription and then used in the "characteristic.on(data)" method to read the real data after the "data changed" trigger came ... 

Whats your info on how many parallel connections can be maintained at the same time?

So here my idea and would be great to get your opinion:

I simply add logic so that lib maintains one connection per type for all subscriptions and also the list of subscribed entities and removes stuff here when someone unsubscribes. when last is unsubscribed also the connection will be closed. Additionally I add a way to "unsubscribe all"

Because on HTTP it should be easier that way and Gatt you have the "subscription persistant connections" plus the one to read data, so basically "the same just different" and on BLE it is more important to clean up bia unsubscribe.

Makes that sense?

**Comment by Apollon77** [comment]
Thanks. I hope I can sometimes mention you to get a second opionion (if you have time) and thank you for all your work done so far - stepping in this shoes will be not that hard :-)

**Comment by Apollon77** [comment]
I did some adjustments in the GitHub version ...
