### ISSUE TITLE
Pairing with Homekit Simulator returns error 1 on M6

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/hap-controller-node#53]
Find out why

**Comment by Apollon77** [comment]
Interestingly it works with "Out in the wild" devoces ... but not with the Homekit Simulator ... no idea why till now

**Comment by rcoletti116** [comment]
Following and commenting to show interest. There are several homebridge plugins that have attempted to use this package, but pairing fails with the same error.

**Comment by Apollon77** [comment]
> There are several homebridge plugins that have attempted to use this package, but pairing fails with the same error.

Really? Where are issues? Where are your logs? Where are questions about it? Details?
I also have this library in use and no one so far reported this issue so I was not investing time because was "just" the simulator.

Please create proper issues with infos and logs. Start process with "DEBUG=hap* node..."

**Comment by NebzHB** [comment]
Hi, 

i've tried to connect to Homekit Accessory Simulator 4.0 (135.3) and it's working fine :)

BR's

**Comment by Apollon77** [comment]
iiinteresting ... amybe I just need to update my Simulator :-)  (my main fun is right now that my macOS is not longer scanning because of a bug which is just fixed in next macOS update ... grmpf), but good to know

**Comment by Apollon77** [comment]
PS: From which xcode additional package this is?

**Comment by NebzHB** [comment]
Additional Tools for Xcode package
